name: build

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: |
        yarn install
    - name: Run tests (if not on Windows)
      if: "!startsWith(matrix.os,'windows')"
      run: |
        yarn run test
    - name: Build and lint
      run: |
        yarn run build
        yarn run lint
      env:
        CI: true

