name: docs

on:
  push:
    tags:
      - "*"

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.x
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
      - name: Generate docs
        run: |
          npm run build
          npm run docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
